export const SORTING_GET_STREAMERS = 'SORTING_GET_STREAMERS',
             SET_SORT_STREAM = 'SET_SORT_STREAM',
             EDIT_RECIPE = 'EDIT_RECIPE',
             UPDATE_RECIPE = 'UPDATE_RECIPE',
             CREATE_RECIPE = 'CREATE_RECIPE',
             DELETE_RECIPE = 'DELETE_RECIPE',
             SAVE_NEW_RECIPE = 'SAVE_NEW_RECIPE',
             TOGGLE_MODAL = 'TOGGLE_MODAL'

